### ISSUE TITLE
NS1 Provider assumes existence of meta notes when used as source

### ISSUE THREAD

**Issue by flz** [octodns/octodns-ns1#17]
I'm trying to run octodns to do a backup of the NS1 config and it's failing on records with filter chains.

Here's the test configuration:

```bash
$ cat test.yaml
---
manager:
  max_workers: 2

providers:
  yaml:
    class: octodns.provider.yaml.YamlProvider
    directory: ./yaml
    default_ttl: 3600
    enforce_order: True
  ns1:
    class: octodns_ns1.Ns1Provider
    api_key: xxx

zones:
  test-ft.com.:
    sources:
      - ns1
    targets:
      - yaml
```

Here's the error:
```bash
$ docker run -v "$(pwd):/octodns" --workdir /octodns octodns/ns1:2022.01-beta2 octodns-sync --config-file /octodns/test.yaml
2022-03-24T17:28:51  [140698882004800] INFO  Manager __init__: config_file=/octodns/test.yaml
2022-03-24T17:28:51  [140698882004800] INFO  Manager __init__:   max_workers=2
2022-03-24T17:28:51  [140698882004800] INFO  Manager __init__:   include_meta=False
2022-03-24T17:28:51  [140698882004800] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=True, force=False, plan_output_fh=<stdout>
2022-03-24T17:28:51  [140698882004800] INFO  Manager sync:   zone=test-ft.com.
2022-03-24T17:28:51  [140698882004800] INFO  Manager sync:   sources=['ns1'] -> targets=['yaml']
2022-03-24T17:28:51  [140698862499584] WARNING Ns1Provider[ns1] Cannot parse foo.test-ft.com dynamic record due to missing pool name in first answer note, treating it as an empty record
Traceback (most recent call last):
  File "/opt/octodns/env/bin/octodns-sync", line 8, in <module>
    sys.exit(main())
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/cmds/sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_sources=args.source,
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/manager.py", line 413, in sync
    ps, d = future.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/manager.py", line 259, in _populate_and_plan
    source.populate(zone, lenient=lenient)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns_ns1/__init__.py", line 907, in populate
    record = Record.new(zone, name, data, source=self, lenient=lenient)
  File "/opt/octodns/env/lib/python3.10/site-packages/octodns/record/__init__.py", line 121, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record foo.test-ft.com.
  - missing value
```

Here's the record, I simply created a CNAME via the NS1 Portal, added SELECT_FIRST_N to the filter chain and two answers with two different georegions:

```bash
$  curl -sH 'X-NSONE-Key: xxx' https://api.nsone.net/v1/zones/test-ft.com/foo.test-ft.com/CNAME | jq -C
{
  "domain": "foo.test-ft.com",
  "zone": "test-ft.com",
  "id": "123",
  "use_client_subnet": true,
  "answers": [
    {
      "answer": [
        "FOO"
      ],
      "meta": {
        "georegion": [
          "US-EAST"
        ]
      },
      "id": "234"
    },
    {
      "answer": [
        "BAR"
      ],
      "meta": {
        "georegion": [
          "EUROPE"
        ]
      },
      "id": "345"
    }
  ],
  "override_ttl": false,
  "regions": {},
  "meta": {},
  "link": null,
  "filters": [
    {
      "filter": "select_first_n",
      "config": {
        "N": "1"
      }
    }
  ],
  "ttl": 3600,
  "tier": 2,
  "type": "CNAME",
  "networks": [
    0
  ]
}
```

**Comment by ross** [comment]
The provider shouldn't outright fail, and should at least warn about that record not being supported and potentially include a "simple" version of it. It's almost certain octoDNS won't support the manually created record with filter chains as it's unlikely to match octoDNS's "dynamic" semantics. I'll take a look at manually creating a similar record and see what can be done to prevent the errors.

**Comment by ross** [comment]
So after looking into it further I think the behavior above is expected, there's an "invalid" record b/c octoDNS doesn't support the filter chains on it. I added a test case for the data exactly as you provided it over in https://github.com/octodns/octodns-ns1/pull/18, but I don't think it'll be needed to address what you ran into.

There's actually `octodns-dump` which is specifically intended for the "initial" dump of records out of a provider(s) into yaml. That command has a `--lenient` flag built-in that would continue to warn about the problematic record, but continue with a placeholder for it. To use it you'll want to flip your zone yaml to:

```yaml
zones:
  test-ft.com.:
    sources:
      - yaml
    targets:
      - ns1
```

and then run something like:

```console
$ docker run -v "$(pwd):/octodns" --workdir /octodns octodns/ns1:2022.01-beta2 octodns-dump --config-file /octodns/test.yaml --output-dir <somewhere> --lenient test-ft.com. ns1`
```

That'll create a set of yaml files that include all the records in NS1 for that zone to the best of octoDNS's ability. It will warn for all of the stuff that it encounters that can't be reproduced like `foo.test-ft.com.`. 

Since octoDNS doesn't support your filterchain setup you won't be able to run `octodns-sync` to push that yaml up to ns1 and get the setup you currently have. If you were to plan it you'd get errors about missing values. If you want to switch your advanced records to use octoDNS's `dynamic` semantics, https://github.com/octodns/octodns/blob/master/docs/dynamic_records.md, you could edit the Yaml to configure things and then do a sync to plan and eventually a sync with `--doit` when you're ready to make the changes. 

If you don't want to adopt octoDNS's schema then you'd essentially have a backup of everything except those "advanced" records.
