### ISSUE TITLE
octodns-dump fails with geo DNS

### ISSUE THREAD

**Issue by jimaek** [octodns/octodns-ns1#27]
```
root@ansible2:~/octodns# octodns-dump --config-file=global-prod.yaml --output-dir=jsdelivr jsdelivr.net. ns1
2022-12-14T17:43:56  [140438021591040] INFO  Manager __init__: config_file=global-prod.yaml (octoDNS 0.9.21)
2022-12-14T17:43:56  [140438021591040] INFO  Manager _config_executor: max_workers=2
2022-12-14T17:43:56  [140438021591040] INFO  Manager _config_include_meta: include_meta=False
2022-12-14T17:43:56  [140438021591040] INFO  Manager __init__: global_processors=[]
2022-12-14T17:43:56  [140438021591040] INFO  Manager __init__: provider=config (octodns.provider.yaml 0.9.21)
2022-12-14T17:43:56  [140438021591040] INFO  Manager __init__: provider=ns1 (octodns_ns1 0.0.2)
2022-12-14T17:43:56  [140438021591040] INFO  Manager dump: zone=jsdelivr.net., output_dir=jsdelivr, output_provider=None, lenient=False, split=False, sources=['ns1']
2022-12-14T17:43:56  [140438021591040] INFO  Manager dump: using custom YamlProvider
2022-12-14T17:43:57  [140438021591040] WARNING Ns1Provider[ns1] Cannot parse cdn.jsdelivr.net dynamic record due to missing pool name in first answer note, treating it as an empty record
Traceback (most recent call last):
  File "/usr/local/bin/octodns-dump", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/octodns/cmds/dump.py", line 48, in main
    manager.dump(
  File "/usr/local/lib/python3.10/dist-packages/octodns/manager.py", line 755, in dump
    source.populate(zone, lenient=lenient)
  File "/usr/local/lib/python3.10/dist-packages/octodns_ns1/__init__.py", line 907, in populate
    record = Record.new(zone, name, data, source=self, lenient=lenient)
  File "/usr/local/lib/python3.10/dist-packages/octodns/record/__init__.py", line 153, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record cdn.jsdelivr.net.
  - missing value
```

I am trying to dump my config but it fails. The config is pretty basic, just a default record and some overrides based on GEO. Filter chain https://dl.dropboxusercontent.com/s/7awv50drgrsad6u/chrome_2022-12-14_18-50-57.png

Any ideas?

**Comment by ross** [comment]
Unfortunately octoDNS doesn't support dumping arbitrary dynamic/advanced records from providers since the breath of what's supported is so vast and different across providers. It's focus is on defining a unified idea of `dynamic`, https://github.com/octodns/octodns/blob/main/docs/dynamic_records.md, that can be implemented ~identically across providers. 

You might try adding the `--lenient` arg to the dump to get octoDNS to try and do what it can with those records. It may be able to dump the parts of them it supports, but the records with Geo targeting definitely will not be correct in the Yaml. That should otherwise give you a starting point that matches what's in NS1 and from there you can edit the Yaml and assuming you're able to convert to octoDNS's idea of dynamic you could hand modify the special records to suit.

**Comment by jimaek** [comment]
I see, thank you for the explanation :)
